name: aplicacion_skillwask
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dependencias para login con Google
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  http: ^1.2.0 
  google_sign_in: ^6.2.1
  image_picker: ^1.2.1
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/IconoSkillSwap.png"
  image_path_ios: "assets/IconoSkillSwap.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Fondo_SkillSwap.png
    - assets/icono.png
    - assets/icon1.png
    - assets/Chatbot_SkillSwap.png
    - assets/Chatbot SkillSwap re.png